server:
  port: 8000

spring:
  application:
    name: apigateway-service
  profiles:
    active: native
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: members
          uri: http://member.camping
          #uri: http://localhost:8080
          predicates:
            - Path=/members/**
          filters:
            - AuthorizationHeaderFilter
        - id: login
          uri: http://member.camping
          predicates:
            - Path=/login
        - id: signon
          uri: http://member.camping
          predicates:
            - Path=/signon
        - id: booking
          #uri: http://camping-gaja-go.com/
          uri: http://booking.camping
          predicates:
            - Path=/booking/**
          filters:
 #           - AuthorizationHeaderFilter


#token:
#  secret: user_token

#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh, health, beans, httptrace, busrefresh, info, metrics, prometheus